-- Schema do banco do TENANT (Postgres) — piloto uCadBancos.
-- Mapeado da tabela BANCOS do legado Oracle (oracle-to-postgres-recon.md):
--   NUMBER→integer, VARCHAR2→varchar, CHAR(2)→char(2), TIMESTAMP(6)→timestamptz.
-- PK por sequence (espelha a geração app-side do legado).

CREATE SEQUENCE IF NOT EXISTS seq_bancos_codbco;

CREATE TABLE IF NOT EXISTS bancos (
  codbco            integer PRIMARY KEY DEFAULT nextval('seq_bancos_codbco'),
  agencia           varchar(10),
  banco             varchar(50) NOT NULL,
  cidade            varchar(50) NOT NULL,
  uf                char(2),
  usultalteracao    integer,
  dtultimalteracao  timestamptz,
  dtcadastro        timestamptz,
  agencia_cedente   integer,
  codbcoblt         integer,
  convenio          integer,
  carteira_cobranca integer,
  variacao_carteira integer
);
ALTER SEQUENCE seq_bancos_codbco OWNED BY bancos.codbco;

-- View de pesquisa GET_BANCOS (aliases idênticos ao legado: codigo, codigo_banco).
CREATE OR REPLACE VIEW get_bancos AS
SELECT banco, agencia, cidade,
       codbco    AS codigo,
       codbcoblt AS codigo_banco,
       convenio, carteira_cobranca, variacao_carteira
FROM bancos;

-- Outbox de replicação (espelha REM_BANCOS→REMESSA_SERVER).
CREATE TABLE IF NOT EXISTS outbox (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo       varchar(10) NOT NULL,
  tabela     varchar(64) NOT NULL,
  chave      integer NOT NULL,
  campochave varchar(64) NOT NULL,
  instrucao  text NOT NULL,
  criado_em  timestamptz NOT NULL DEFAULT now()
);
