-- 193 — folds da carga das 70 tabelas que o plano antigo não cobria (§7s do plano de carga), medidos em PRODUÇÃO.
--
-- 1) `arquivo_remessa_areceber`: o legado reutiliza o NOME do arquivo de remessa (69 nomes repetidos, até 3×,
--    inclusive na mesma conta) e não tem `codempresa`. O índice `ux_arq_remessa_nome (codempresa, nomearquivo)`
--    é proteção NOSSA para o que o app gera — fica, mas só para linhas novas (mesmo padrão das migs 173/182/
--    183/186/188: `origem_legado`). A carga carimba origem_legado='S'.
ALTER TABLE arquivo_remessa_areceber ADD COLUMN IF NOT EXISTS origem_legado char(1);
DROP INDEX IF EXISTS ux_arq_remessa_nome;
CREATE UNIQUE INDEX IF NOT EXISTS ux_arq_remessa_nome ON arquivo_remessa_areceber (codempresa, nomearquivo)
  WHERE coalesce(origem_legado, 'N') <> 'S';

-- 2) `indexador_tributario`: os NOT NULL de aliquota_dest / icm_fonte / mva / reducao vieram da mig 008, ANTES do
--    recon, como suposição. No legado as quatro são NULLABLE e a alíquota interna se chama ALIQUOTA (renomeada na
--    extração). NOT NULL que o legado não tem SAI — a resolução de figura fiscal lê com `Number(...)`, e `Number(null)` é 0,
--    o mesmo neutro que a carga usaria.
ALTER TABLE indexador_tributario ALTER COLUMN aliquota_dest DROP NOT NULL;
ALTER TABLE indexador_tributario ALTER COLUMN icm_fonte     DROP NOT NULL;
ALTER TABLE indexador_tributario ALTER COLUMN mva           DROP NOT NULL;
ALTER TABLE indexador_tributario ALTER COLUMN reducao       DROP NOT NULL;

-- 3) `log_liberacoes.id` era GENERATED ALWAYS: a carga precisa gravar o id do legado (6.288 liberações) e o app
--    continua deixando o banco gerar. BY DEFAULT faz os dois; a sequência é reposicionada no fim da carga.
ALTER TABLE log_liberacoes ALTER COLUMN id SET GENERATED BY DEFAULT;
