-- 382 — RBAC fiel ao legado (docs/05-migration-engineering/permissoes-de-controle.md, "Atos sem opção própria"): 46 atos que o
-- Apollo guardava com uma opção inventada (BTNESTORNAR, BTNPROCESSAR, BTNREABRIR…) que não existe na PERMISSOES da produção —
-- depois da carga ninguém os faria. Passam a exigir o que o legado exige: o gate da tela quando o ato não tem componente com
-- Tag 1, ou a opção do componente/da checagem por código quando tem. Fixture do seed (operador 7, lojas 1 e 2); a carga traz
-- as PERMISSOES reais.
INSERT INTO permissoes (form, opcao, codoperador, codempresa)
SELECT x.form, x.opcao, 7, e.emp
  FROM (VALUES ('FRMETIQUETA', 'FRMETIQUETA'), ('FRMETIQUETA', 'BTNCONSULTAPRECO'), ('FRMETIQUETA', 'BTNADICIONARREGISTRO'),
               ('FRMEXPORTABALANCA', 'FRMEXPORTABALANCA'), ('FRMEXPORTABALANCA', 'BTNEXPORTAR'),
               ('FRMCADAGENDAPROMOCAO', 'FRMCADAGENDAPROMOCAO'), ('FRMCADAGENDAPROMOCAO', 'ENCERRARPROMOCAO'),
               ('FRMBAIXACARTAO', 'BTNCONSULTA'), ('FRMDESCONTOTITULO', 'FRMDESCONTOTITULO'),
               ('FRMDESCONTOTITULO', 'BTNADICIONARREGISTRO'), ('FRMDESCONTOTITULO', 'BTNCONSULTA'),
               ('FRMCADPERFILOPERADOR', 'FRMCADPERFILOPERADOR'), ('FRMCADPERFILOPERADOR', 'BTNGRAVAR'),
               ('FRMCADCOTACAO', 'FRMCADCOTACAO'), ('FRMCADCOTACAO', 'BTNGRAVAR'), ('FRMNF', 'FRMNF'), ('FRMNF', 'BTNGRAVAR'),
               ('FRMCADEMPRESA', 'FRMCADEMPRESA'), ('FRMCADEMPRESA', 'BTNGRAVAR'),
               ('FRMAJUSTEESTOQUE', 'FRMAJUSTEESTOQUE'), ('FRMANALISECOMPORTAMENTO', 'FRMANALISECOMPORTAMENTO'),
               ('FRMAPURACAOPISCOFINS', 'FRMAPURACAOPISCOFINS'), ('FRMBAIXACARTAO', 'FRMBAIXACARTAO'),
               ('FRMCADCLASSTRIBIBSCBS', 'FRMCADCLASSTRIBIBSCBS'), ('FRMCADPEDIDODEVOLUCAOCOMPRAS', 'FRMCADPEDIDODEVOLUCAOCOMPRAS'),
               ('FRMCONCILIACAOBANCARIA', 'FRMCONCILIACAOBANCARIA'), ('FRMCONFBOLETO', 'FRMCONFBOLETO'),
               ('FRMCONFIGINTEGRACAOCONTABIL', 'FRMCONFIGINTEGRACAOCONTABIL'), ('FRMCONGELAESTOQUE', 'FRMCONGELAESTOQUE'),
               ('FRMCONSRCBBX', 'FRMCONSRCBBX'), ('FRMDEVOLUCAOVENDAS', 'FRMDEVOLUCAOVENDAS'), ('FRMPEDIDOCOMPRA', 'FRMPEDIDOCOMPRA'),
               ('FRMPRECIFICACAONF', 'FRMPRECIFICACAONF'), ('FRMRELDRECONTABIL', 'FRMRELDRECONTABIL'),
               ('FRMRELRAZAOCONTABIL', 'FRMRELRAZAOCONTABIL'), ('FRMGERARFINANCEIROLOTE', 'FRMGERARFINANCEIROLOTE')) AS x(form, opcao)
 CROSS JOIN (VALUES (1), (2)) AS e(emp)
ON CONFLICT DO NOTHING;
