/**
 * Os campos do cadastro de empresas (UCadEmpresa) que a tela do Apollo não tinha — gerado do `UCadEmpresa.dfm` (rótulo, aba, itens dos
 * combos) e do schema do destino (tipo, tamanho); os do binário novo (integrações) sem rótulo no fonte de 2020 levam o nome da coluna.
 * Fora: o que o sistema mantém (NSU, carimbos, hashes, as datas de contingência do PDV), os certificados (binário) e as senhas de
 * operação, que o Apollo guarda em hash (`senha-operacao`). `segredo`: gravável, nunca devolvido na leitura.
 */
export type TipoCampoEmpresa = 'texto' | 'inteiro' | 'numero' | 'sn' | 'opcao' | 'data';
export interface CampoEmpresaLegado {
  coluna: string;
  rotulo: string;
  aba: string;
  tipo: TipoCampoEmpresa;
  max?: number;
  opcoes?: ReadonlyArray<readonly [string, string]>;
  segredo?: boolean;
}
export const EMPRESA_CAMPOS_LEGADO: readonly CampoEmpresaLegado[] = [
  { coluna: 'alertafiscal_ambiente', rotulo: "Alertafiscal ambiente", aba: "Integrações", tipo: 'texto', max: 1 },
  { coluna: 'alertafiscal_idcliente', rotulo: "Alertafiscal idcliente", aba: "Integrações", tipo: 'inteiro' },
  { coluna: 'alertafiscal_tempo_envio_prod', rotulo: "Alertafiscal tempo envio prod", aba: "Integrações", tipo: 'inteiro' },
  { coluna: 'alertafiscal_tempo_receb_prod', rotulo: "Alertafiscal tempo receb prod", aba: "Integrações", tipo: 'inteiro' },
  { coluna: 'alertafiscal_tempo_retorno_api', rotulo: "Alertafiscal tempo retorno api", aba: "Integrações", tipo: 'inteiro' },
  { coluna: 'alertafiscal_token', rotulo: "Alertafiscal token", aba: "Integrações", tipo: 'texto', max: 1000, segredo: true },
  { coluna: 'alertafiscal_url_consulta', rotulo: "Alertafiscal url consulta", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'alertafiscal_url_consulta_prod', rotulo: "Alertafiscal url consulta prod", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'alertafiscal_url_webhook', rotulo: "Alertafiscal url webhook", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'alertafiscal_url_webhook_prod', rotulo: "Alertafiscal url webhook prod", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'aluguel', rotulo: "Aluguel", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'assunto', rotulo: "Assunto", aba: "Email", tipo: 'texto', max: 150 },
  { coluna: 'atucomposicao', rotulo: "Atualiza composição do produto", aba: "Configurações", tipo: 'sn', max: 1 },
  { coluna: 'atudcomposicao', rotulo: "Atualiza decomposição do produto", aba: "Configurações", tipo: 'sn', max: 1 },
  { coluna: 'autenticacao_mdfe', rotulo: "Certificado", aba: "MDF-e", tipo: 'texto', max: 255, segredo: true },
  { coluna: 'auth_fgf_api', rotulo: "Auth fgf api", aba: "Integrações", tipo: 'texto', max: 1000, segredo: true },
  { coluna: 'auth_fgf_api_v2', rotulo: "Auth fgf api v2", aba: "Integrações", tipo: 'texto', max: 4000, segredo: true },
  { coluna: 'campocomposicao', rotulo: "Campo valor para formar a composição", aba: "Configurações", tipo: 'opcao', max: 7, opcoes: [["VRVENDA", "Valor da venda"], ["VRCUSTO", "Valor do custo"]] },
  { coluna: 'cancelmax', rotulo: "Cancelamento Máximo R$", aba: "Configurações", tipo: 'numero' },
  { coluna: 'ccacresjuro', rotulo: "Juro  acresc. pago", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'ccacresjuroobtido', rotulo: "Juro acrec. obtido", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'ccdesconto', rotulo: "Desconto concedido", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'ccdescontoobtido', rotulo: "Desconto obtido", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'cctesouraria', rotulo: "Cctesouraria", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'certificado_cte_senha', rotulo: "Senha Certificado", aba: "CT-e", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'certificado_senha', rotulo: "Senha Certificado", aba: "NFC-e", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'certificado_senha_mdfe', rotulo: "Senha Certificado", aba: "MDF-e", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'chamafila_url', rotulo: "Url Base", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'cnae_principal', rotulo: "CNAE principal", aba: "Outras configurações", tipo: 'texto', max: 7 },
  { coluna: 'cnae_secundario', rotulo: "CNAE Secundário", aba: "Outras configurações", tipo: 'texto', max: 7 },
  { coluna: 'cod_ajus_icms_st', rotulo: "Código do ajuste ICMS ST", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'cod_ajus_ipi', rotulo: "Código do ajuste IPI", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'cod_ajus_sn', rotulo: "Código", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'cod_estabelecimento_cielo', rotulo: "Código do estabelecimento (Conciliação Cielo)", aba: "Configurações financeiras", tipo: 'texto', max: 20 },
  { coluna: 'cod_estabelecimento_redecard', rotulo: "Código do estabelecimento (Conciliação Redecard)", aba: "Configurações financeiras", tipo: 'texto', max: 50 },
  { coluna: 'codcentralbalcao', rotulo: "Codcentralbalcao", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'codconta_baixa_correspondente', rotulo: "Codconta baixa correspondente", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codconta_baixa_recarga', rotulo: "Codconta baixa recarga", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codconta_pagamento', rotulo: "Codconta pagamento", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'codempresa_finan', rotulo: "Codempresa finan", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'codfornecedor_correspondente', rotulo: "Fornecedor referente à correspondente bancário", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codfornecedor_recarga', rotulo: "Fornecedor referente à recarga", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codfornecedor_trocosolidario', rotulo: "Fornecedor referente à troco solidário", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codfornecedor_voucher', rotulo: "Fornecedor referente à voucher", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codigoempresawl', rotulo: "Codigoempresawl", aba: "Integrações", tipo: 'texto', max: 5 },
  { coluna: 'codoperador_autoatendimento', rotulo: "Codoperador autoatendimento", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'codperfil_proprietario', rotulo: "Codperfil proprietario", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'codplc_acrescimos_recebidos', rotulo: "Codplc acrescimos recebidos", aba: "Contas a receber, cartões e cheques", tipo: 'inteiro' },
  { coluna: 'codplc_correspondente', rotulo: "Codplc correspondente", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codplc_juros_recebidos', rotulo: "Codplc juros recebidos", aba: "Contas a receber, cartões e cheques", tipo: 'inteiro' },
  { coluna: 'codplc_recarga', rotulo: "Codplc recarga", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codplc_taxa_cartao_paga', rotulo: "Codplc taxa cartao paga", aba: "Contas a receber, cartões e cheques", tipo: 'inteiro' },
  { coluna: 'codplc_taxas_cartao', rotulo: "Codplc taxas cartao", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'codplc_trocosolidario', rotulo: "Codplc trocosolidario", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codplc_voucher', rotulo: "Codplc voucher", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'codplcfechamentoconvenio', rotulo: "Codplcfechamentoconvenio", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'codterminal', rotulo: "Codterminal", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'contacmv', rotulo: "Contacmv", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'contacofre', rotulo: "Contacofre", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'contrapartida', rotulo: "Contrapartida", aba: "Configurações Contábeis", tipo: 'texto', max: 10 },
  { coluna: 'cpf', rotulo: "CPF", aba: "Dados cadastrais", tipo: 'texto', max: 20 },
  { coluna: 'crescevendas_email', rotulo: "E-Mail", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'crescevendas_token', rotulo: "Token", aba: "Integrações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'crescevendas_url', rotulo: "Url Base", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'csc', rotulo: "CSC", aba: "NFC-e", tipo: 'texto', max: 100, segredo: true },
  { coluna: 'csc_id', rotulo: "CSC ID", aba: "NFC-e", tipo: 'inteiro' },
  { coluna: 'csc_id_teste', rotulo: "CSC ID", aba: "NFC-e", tipo: 'inteiro' },
  { coluna: 'csc_teste', rotulo: "CSC", aba: "NFC-e", tipo: 'texto', max: 100, segredo: true },
  { coluna: 'cta_caixa', rotulo: "Cta caixa", aba: "Outras configurações", tipo: 'inteiro' },
  { coluna: 'cte_autenticacao', rotulo: "Certificado", aba: "CT-e", tipo: 'texto', max: 255, segredo: true },
  { coluna: 'data_abertura', rotulo: "Data Abertura", aba: "Dados cadastrais", tipo: 'data' },
  { coluna: 'desabilita_remessa', rotulo: "Desabilita Remessas", aba: "Configurações", tipo: 'sn', max: 1 },
  { coluna: 'despfederativas', rotulo: "Despesas Feder.%", aba: "Configurações", tipo: 'numero' },
  { coluna: 'dlm_pedido_compra', rotulo: "Dlm pedido compra", aba: "Outras configurações", tipo: 'texto', max: 2 },
  { coluna: 'email', rotulo: "E-mail", aba: "Contabilista", tipo: 'texto', max: 100 },
  { coluna: 'email_aut_ssl', rotulo: "Autenticação SSL", aba: "Email", tipo: 'sn', max: 1 },
  { coluna: 'email_aut_tls', rotulo: "Autenticação TLS", aba: "Email", tipo: 'sn', max: 1 },
  { coluna: 'email_contador', rotulo: "Enviar email ao contador quando enviar NF-e", aba: "Configurações", tipo: 'sn', max: 1 },
  { coluna: 'email_senha', rotulo: "Email senha", aba: "Outras configurações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'email_texto_nfc', rotulo: "Texto para E-Mail", aba: "NFC-e", tipo: 'texto', max: 600 },
  { coluna: 'fab_escala_nao_relevante', rotulo: "Fab escala nao relevante", aba: "Outras configurações", tipo: 'sn', max: 1 },
  { coluna: 'faturamentopedido', rotulo: "Data Processamento Pedido", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["V", "DATA VENDA"], ["P", "DATA PROCESSAMENTO"]] },
  { coluna: 'faturapedidodireto', rotulo: "Fatura pedido / OS direto", aba: "Configurações", tipo: 'sn', max: 1 },
  { coluna: 'fechamento_caixa', rotulo: "Realiza Fechamento de Caixa", aba: "Outras configurações", tipo: 'opcao', max: 1, opcoes: [["S", "SIM"], ["N", "NAO"]] },
  { coluna: 'filialempresawl', rotulo: "Filialempresawl", aba: "Integrações", tipo: 'texto', max: 3 },
  { coluna: 'filtrapdv', rotulo: "Consultar tesouraria filtrando por PDV", aba: "Configurações", tipo: 'opcao', max: 3, opcoes: [["SIM", "SIM"], ["NAO", "NAO"]] },
  { coluna: 'fone2', rotulo: "Fax", aba: "Dados cadastrais", tipo: 'texto', max: 20 },
  { coluna: 'grupotensao', rotulo: "Grupo de tensão elétrica", aba: "Outras configurações", tipo: 'opcao', max: 2, opcoes: [["01", "01 - A1 - ALTA TENSÃO (230 kV OU MAIS)"], ["02", "02 - A2 - ALTA TENSÃO (88 a 138 kV)"], ["03", "03 - A3 - ALTA TENSÃO (69 kV)"], ["04", "04 - A3a - ALTA TENSÃO (30 kV a 44kV)"], ["05", "05 - A4 - ALTA TENSÃO (2,3 kV a 25kV)"], ["06", "06 - AS - Alta Tensão Subterrâneo 06"], ["07", "07 - B1 - RESIDENCIAL 07"], ["08", "08 - B1 - RESIDENCIAL BAIXA RENDA 08"], ["09", "09 - B2 - RURAL 09"], ["10", "10 - B2 - COOPERATIVA DE ELETRIFICAÇÃO RURAL"], ["11", "11 - B2 - SERVIÇO PÚBLICO DE IRRIGAÇÃO"], ["12", "12 - B3 - DEMAIS CLASSES"], ["13", "13 - B4a - ILUMINAÇÃO PUBLICA REDE DE DISTRIBUIÇÃO"], ["14", "14 - B4b - ILUMINAÇÃO PUBLICA BULBO DE LAMPADA"]] },
  { coluna: 'hab_cod_beneficio_fis', rotulo: "Hab cod beneficio fis", aba: "Outras configurações", tipo: 'sn', max: 1 },
  { coluna: 'idcliente_fgf', rotulo: "Id. Usuário", aba: "Integrações", tipo: 'inteiro' },
  { coluna: 'idpgto', rotulo: "Forma de pagamento de quebra de caixa", aba: "Caixa", tipo: 'inteiro' },
  { coluna: 'idsuporteborba', rotulo: "Id Suporte Borba", aba: "Dados cadastrais", tipo: 'texto', max: 30 },
  { coluna: 'indice_ativ', rotulo: "Indice de atividade", aba: "Outras configurações", tipo: 'opcao', opcoes: [["0", "0 - Industrial ou equiparado a industrial;"], ["1", "1 - Outros."]] },
  { coluna: 'insc_mun', rotulo: "IM", aba: "Dados cadastrais", tipo: 'texto', max: 30 },
  { coluna: 'integracao', rotulo: "Tipo de Integração", aba: "Configurações Contábeis", tipo: 'texto', max: 20 },
  { coluna: 'integrante', rotulo: "Sistema Integrante", aba: "Configurações Contábeis", tipo: 'texto', max: 10 },
  { coluna: 'izio_token', rotulo: "Token", aba: "Integrações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'izio_url', rotulo: "Url Base", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'lcto_contabil', rotulo: "Tipo de Lançamento", aba: "Configurações Contábeis", tipo: 'texto', max: 10 },
  { coluna: 'lcto_financeiro', rotulo: "Lcto financeiro", aba: "Outras configurações", tipo: 'sn', max: 1 },
  { coluna: 'loja_email', rotulo: "Loja email", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'loja_token', rotulo: "Loja token", aba: "Integrações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'loja_url', rotulo: "Loja url", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'mascaraplc', rotulo: "Mascara P.L.C", aba: "Configurações", tipo: 'texto', max: 30 },
  { coluna: 'mensagempromocao', rotulo: "Mensagem promoção (PDV)", aba: "Outras configurações", tipo: 'texto', max: 255 },
  { coluna: 'mercafacil_idpgto', rotulo: "Mercafacil idpgto", aba: "Integrações", tipo: 'numero' },
  { coluna: 'mercafacil_token', rotulo: "Mercafacil token", aba: "Integrações", tipo: 'texto', max: 1000, segredo: true },
  { coluna: 'mercafacil_url', rotulo: "Mercafacil url", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'meta_compra', rotulo: "Meta de Compra", aba: "Configurações", tipo: 'numero' },
  { coluna: 'modelo_duplicata', rotulo: "Modelo Duplicata", aba: "Configurações", tipo: 'opcao', opcoes: [["1", "PADRÃO"], ["2", "NRONF + QTDEPARCELAS"]] },
  { coluna: 'motivo_contingencia_nfc', rotulo: "Motivo de Contingência", aba: "NFC-e", tipo: 'texto', max: 200 },
  { coluna: 'nfce_autenticacao', rotulo: "Certificado", aba: "NFC-e", tipo: 'texto', max: 255, segredo: true },
  { coluna: 'nome', rotulo: "Nome", aba: "Contabilista", tipo: 'texto', max: 200 },
  { coluna: 'nome_loja_tricard', rotulo: "Nome da loja (Conciliação Tricard)", aba: "Configurações financeiras", tipo: 'texto', max: 100 },
  { coluna: 'nomeloja', rotulo: "Nome da loja (Conciliação E-Extrato)", aba: "Configurações financeiras", tipo: 'texto', max: 100 },
  { coluna: 'numeitensnota', rotulo: "Qtde. Itens NF", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'numero_historico', rotulo: "Nº Registros Histórico", aba: "Configurações", tipo: 'inteiro' },
  { coluna: 'numeroinicial_mdfe', rotulo: "Nº inicial do MDF-e", aba: "MDF-e", tipo: 'texto', max: 3 },
  { coluna: 'pc_curva_abc_a_qtde', rotulo: "Pc curva abc a qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_abc_b_qtde', rotulo: "Pc curva abc b qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_abc_c_qtde', rotulo: "Pc curva abc c qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_abc_d', rotulo: "Pc curva abc d", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_abc_d_qtde', rotulo: "Pc curva abc d qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_abc_e', rotulo: "Pc curva abc e", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_abc_e_qtde', rotulo: "Pc curva abc e qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_a_qtde', rotulo: "Pc curva comp a qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_b_qtde', rotulo: "Pc curva comp b qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_c_qtde', rotulo: "Pc curva comp c qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_d', rotulo: "Pc curva comp d", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_d_qtde', rotulo: "Pc curva comp d qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_e', rotulo: "Pc curva comp e", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pc_curva_comp_e_qtde', rotulo: "Pc curva comp e qtde", aba: "Configurações", tipo: 'numero' },
  { coluna: 'pedcompra', rotulo: "Pedido de Compra", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["V", "Vendas"], ["P", "Pedidos"]] },
  { coluna: 'percent_compra_prop', rotulo: "Percent compra prop", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'percent_multa', rotulo: "% Multa", aba: "Configurações", tipo: 'numero' },
  { coluna: 'percentual_acresc_prod', rotulo: "Percentual acresc prod", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'perfilsped', rotulo: "Perfil para SPED", aba: "Outras configurações", tipo: 'opcao', max: 1, opcoes: [["A", "A"], ["B", "B"], ["C", "C"]] },
  { coluna: 'pisconfis', rotulo: "Pis / Cofins%", aba: "Configurações", tipo: 'numero' },
  { coluna: 'porta', rotulo: "Porta", aba: "Email", tipo: 'inteiro' },
  { coluna: 'preconf', rotulo: "Atualizar preço ao processar Nota", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["O", "On-line"], ["L", "Em lote"]] },
  { coluna: 'preen_ncm', rotulo: "Preenchimento NCM", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["C", "COMPLETO"], ["G", "GENERO"]] },
  { coluna: 'ramoatividade', rotulo: "Ramo de atividade", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["S", "SUPERMERCADO"], ["O", "OUTROS"]] },
  { coluna: 'regime_lote', rotulo: "Regime de Lote", aba: "Configurações Contábeis", tipo: 'texto', max: 10 },
  { coluna: 'remessaativa', rotulo: "Remessaativa", aba: "Outras configurações", tipo: 'sn', max: 1 },
  { coluna: 'responsavel', rotulo: "Responsável", aba: "Dados cadastrais", tipo: 'texto', max: 80 },
  { coluna: 'saida_operadora', rotulo: "Validar Saída Operadora", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["S", "SIM"], ["N", "NAO"]] },
  { coluna: 'salario', rotulo: "Salario", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'scanntech_token', rotulo: "Scanntech token", aba: "Integrações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'segmento', rotulo: "Segmento", aba: "Outras configurações", tipo: 'opcao', max: 20, opcoes: [["PADRAO", "PADRÃO"], ["INDUSTRIA", "INDÚSTRIA"]] },
  { coluna: 'senha_email', rotulo: "Senha", aba: "Email", tipo: 'texto', max: 30, segredo: true },
  { coluna: 'separador_duplicata', rotulo: "Separador Duplicata", aba: "Configurações", tipo: 'texto', max: 1 },
  { coluna: 'serie_mdfe', rotulo: "Série do MDF-e", aba: "MDF-e", tipo: 'texto', max: 3 },
  { coluna: 'serie_nfc', rotulo: "Serie nfc", aba: "Outras configurações", tipo: 'texto', max: 3 },
  { coluna: 'seriecte', rotulo: "Série do CT-e", aba: "CT-e", tipo: 'texto', max: 3 },
  { coluna: 'smtp', rotulo: "SMTP", aba: "Email", tipo: 'texto', max: 100 },
  { coluna: 'stef_integrador_cnpj', rotulo: "Stef integrador cnpj", aba: "Integrações", tipo: 'texto', max: 14 },
  { coluna: 'stef_integrador_jwt', rotulo: "Stef integrador jwt", aba: "Integrações", tipo: 'texto', max: 1000, segredo: true },
  { coluna: 'stef_integrador_token', rotulo: "Stef integrador token", aba: "Integrações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'stef_loja_token', rotulo: "Stef loja token", aba: "Integrações", tipo: 'texto', max: 50, segredo: true },
  { coluna: 'suframa', rotulo: "Suframa", aba: "Outras configurações", tipo: 'texto', max: 10 },
  { coluna: 'tef_administrativo_funcao', rotulo: "Tef administrativo funcao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_administrativo_restricao', rotulo: "Tef administrativo restricao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_cartao_funcao', rotulo: "Tef cartao funcao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_cartao_restricao', rotulo: "Tef cartao restricao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_correspondente_funcao', rotulo: "Tef correspondente funcao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_correspondente_restricao', rotulo: "Tef correspondente restricao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_recarga_funcao', rotulo: "Tef recarga funcao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_recarga_restricao', rotulo: "Tef recarga restricao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_voucher_funcao', rotulo: "Tef voucher funcao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'tef_voucher_restricao', rotulo: "Tef voucher restricao", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'texto', rotulo: "Texto", aba: "Email", tipo: 'texto', max: 600 },
  { coluna: 'token_fgf', rotulo: "Token", aba: "Integrações", tipo: 'texto', max: 200, segredo: true },
  { coluna: 'tokenwl', rotulo: "Tokenwl", aba: "Integrações", tipo: 'texto', max: 100, segredo: true },
  { coluna: 'tolerancianf', rotulo: "Série da NF", aba: "Configurações", tipo: 'numero' },
  { coluna: 'tp_ligacao', rotulo: "Tipo de ligação elétrica", aba: "Outras configurações", tipo: 'opcao', opcoes: [["1", "1 - MONOFASICO"], ["2", "2 - BIFASICO"], ["3", "3 - TRIFASICO"]] },
  { coluna: 'tptransp_mdfe', rotulo: "Tipo do Transportador", aba: "MDF-e", tipo: 'opcao', opcoes: [["1", "1 - ETC"], ["2", "2 - TAC"], ["3", "3 - CTC "]] },
  { coluna: 'trigger_estoque', rotulo: "Ativa Trigger Estoque", aba: "Configurações", tipo: 'sn', max: 1 },
  { coluna: 'txadm', rotulo: "Taxa administrativa", aba: "Configurações", tipo: 'numero' },
  { coluna: 'url_fgf_api', rotulo: "Url fgf api", aba: "Integrações", tipo: 'texto', max: 200 },
  { coluna: 'urlbasewl', rotulo: "Urlbasewl", aba: "Integrações", tipo: 'texto', max: 100 },
  { coluna: 'validacaixa', rotulo: "Validar Caixa", aba: "Configurações", tipo: 'opcao', max: 1, opcoes: [["S", "SIM"], ["N", "NAO"]] },
  { coluna: 'valor_cbs', rotulo: "Valor cbs", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'valor_informar_cliente', rotulo: "Valor informar cliente", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'valor_maximo_informar_cliente', rotulo: "Valor maximo informar cliente", aba: "Outras configurações", tipo: 'numero' },
  { coluna: 'valor_perc_multa', rotulo: "Valor perc multa", aba: "Outras configurações", tipo: 'opcao', max: 1, opcoes: [["F", "Valor fixo"], ["P", "Percentual"]] },
  { coluna: 'vlr_produto', rotulo: "Vlr produto", aba: "Outras configurações", tipo: 'numero' },
];
