-- CAPTURA DO V$SQL DA PRODUÇÃO (somente leitura), 06/10/2026 — sql_id 8atxanr5aywa0
-- O SQL que o binário novo do FRMRELENTRADASSAIDAS roda (o fonte de mai/2020 não tem ATIVO_VENDA, QTDE_SAIDA, ULTIMA_NF_ENTRADA, DESCRICAO_FORN).
-- Variante sem a data no agrupamento (CURR.DTVENDA comentado), lojas IN (1). Capturado por scratchpad/vigia_geral.py (padrão 'entsai').

SELECT ATIVO_VENDA,
       ATIVO_COMPRA,
       CODBARRA,
       MAX(TRUNC(DTVENDA)) DTVENDA,
       CODPRODUTO,
       DESCRICAO,
       SUM(QTDE_ENTRADA ) AS QTDE_ENTRADA,
       CAST(SUM(VALOR_ENTRADA)AS NUMBER(15,3)) AS VALOR_ENTRADA,
       CASE
       WHEN SUM(VALOR_ENTRADA) > 0 AND SUM(QTDE_ENTRADA) > 0 THEN CAST(((SUM(VALOR_ENTRADA)) / (SUM(QTDE_ENTRADA))) AS NUMBER(15,3)) 
       ELSE
       0
       END MEDIA_CUSTO,
       SUM(QTDE_SAIDA   ) AS QTDE_SAIDA,
       SUM(VALOR_SAIDA  ) AS VALOR_SAIDA,
       CASE
       WHEN SUM(VALOR_SAIDA) > 0 AND SUM(QTDE_SAIDA) > 0 THEN CAST(((SUM(VALOR_SAIDA) ) / (SUM(QTDE_SAIDA))) AS NUMBER(15,3)) 
       ELSE
       0
       END MEDIA_VENDA,
       CAST(SUM((QTDE_SAIDA    - QTDE_ENTRADA  ))AS NUMBER(15,3)) AS QTDE_DIF,
       cast(SUM((VALOR_SAIDA   - VALOR_ENTRADA ))AS NUMBER(15,3)) AS VALOR_DIF,
       (SELECT SUM(CAST(COALESCE(E.QTDE , 0) AS NUMBER(15,3))) FROM  ESTOQUE E WHERE E.IDPRODUTO  = CURR.CODPRODUTO AND E.IDEMPRESA  = CURR.IDEMPRESA) QTDE_ESTOQUE_LOJA,
       (SELECT SUM(CAST(COALESCE(ED.QTDE , 0) AS NUMBER(15,3))) FROM  ESTOQUE_DEP ED WHERE ED.IDPRODUTO  = CURR.CODPRODUTO AND ED.IDEMPRESA  = CURR.IDEMPRESA) QTDE_ESTOQUE_DEPOSITO,
       (SELECT SUM(CAST(COALESCE(E.QTDE , 0) AS NUMBER(15,3))) FROM  ESTOQUE E WHERE E.IDPRODUTO  = CURR.CODPRODUTO AND E.IDEMPRESA  = CURR.IDEMPRESA) +
       (SELECT SUM(CAST(COALESCE(ED.QTDE , 0) AS NUMBER(15,3))) FROM  ESTOQUE_DEP ED WHERE ED.IDPRODUTO  = CURR.CODPRODUTO AND ED.IDEMPRESA  = CURR.IDEMPRESA) QTDE_ESTOQUE_TOTAL,
       CURR.IDEMPRESA,
       EM.FANTASIA, VRCUSTOREP, VRVENDA, FATORCX,
       CAST((((VRVENDA - VRCUSTOREP)/ NULLIF(VRCUSTOREP,0))*100) AS NUMBER(15,2)) AS MARKUP,
       CAST((((VRVENDA - VRCUSTOREP)/ NULLIF(VRVENDA,0))*100) AS NUMBER(15,2)) AS MARGEM,
       (SELECT NRONF  FROM NF WHERE CODNF = 
       (SELECT MAX(NF.CODNF) FROM NF_PROD NP INNER JOIN NF NF ON NP.CODNF = NF.CODNF
       WHERE NP.CODPRODUTO = CURR.CODPRODUTO AND NF.IDEMPRESA = CURR.IDEMPRESA 
       AND NF.TIPO = 'E' AND NF.PROC = 'S')) ULTIMA_NF_ENTRADA,
      (SELECT DTEMISSAO  FROM NF WHERE CODNF = 
       (SELECT MAX(NF.CODNF) FROM NF_PROD NP INNER JOIN NF NF ON NP.CODNF = NF.CODNF
       WHERE NP.CODPRODUTO = CURR.CODPRODUTO AND NF.IDEMPRESA = CURR.IDEMPRESA 
       AND NF.TIPO = 'E' AND NF.PROC = 'S')) DATA_ULTIMA_NF_ENTRADA,
        DEPARTAMENTO,
       GRUPO,
       SUBGRUPO,
       SESSAO SECAO,
       CODFOR,
       DESCRICAO_FORN
FROM 
(
  SELECT ATIVO_VENDA,
         ATIVO_COMPRA,
         CODBARRA,
         DTVENDA,
         CODPRODUTO,        
         DESCRICAO,
         IDEMPRESA,
         SUM(QTDE_ENTRADA) AS QTDE_ENTRADA,
         SUM(VALOR_ENTRADA) AS VALOR_ENTRADA,
         SUM(QTDE_SAIDA) AS QTDE_SAIDA,
         SUM(VALOR_SAIDA) AS VALOR_SAIDA, VRCUSTOREP, VRVENDA, FATORCX, ORIGEM,
         DEPARTAMENTO,
         GRUPO,
         SUBGRUPO,
         SESSAO,
         CODFOR,
         DESCRICAO_FORN
  FROM (  
    SELECT (SELECT ATIVO FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS ATIVO_VENDA,
           (SELECT ATIVO_COMPRA FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS ATIVO_COMPRA,
           'SAIDA - NF' AS ORIGEM,
           P.CODBARRA AS CODBARRA,
           TRUNC(N.DTCONTABIL) DTVENDA,
           NP.CODPRODUTO,
           P.DESCRICAO, 
           0 AS QTDE_ENTRADA,
           0 AS VALOR_ENTRADA,
           (NP.QUANTIDADE * NP.FATOREMBAL) AS QTDE_SAIDA,
           ( (NP.QUANTIDADE ) * COALESCE(NP.VRCUSTO,0) ) AS VALOR_SAIDA,
           N.IDEMPRESA, (SELECT  VRCUSTOREP FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS VRCUSTOREP,
		   (SELECT  VRVENDA FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS VRVENDA, P.FATORCX,
       D.DESCRICAO DEPARTAMENTO,
       G.DESCRICAO GRUPO,
       SG.DESCRICAO SUBGRUPO,
       SE.DESCRICAO SESSAO,
       P.CODFOR,
       PAR.RAZAO DESCRICAO_FORN
    FROM NF N 
    LEFT JOIN NF_PROD      NP ON NP.CODNF     = N.CODNF
    LEFT JOIN PRODUTOS      P ON P.IDPRODUTO  = NP.CODPRODUTO
    LEFT JOIN FAMILIAS_PROD  D ON D.CODFAMILIA   = P.CODDPTO
    LEFT JOIN FAMILIAS_PROD  G ON G.CODFAMILIA   = P.CODGRUPO
    LEFT JOIN FAMILIAS_PROD SG ON SG.CODFAMILIA  = P.CODSUBGRUPO
    LEFT JOIN FAMILIAS_PROD SE ON SE.CODFAMILIA  = P.CODSECAO
    LEFT JOIN PARCEIROS PAR    ON PAR.CODPARCEIRO = P.CODFOR
    WHERE N.TIPO = 'S' 
    AND TRUNC(N.DTCONTABIL) BETWEEN :D1 AND :D2
    AND N.CFOP IN ('5102','5202','5402','5403','5405','5411','5927','6102','6202','6402','6403','6404','6405','6411','6927')
    AND COALESCE(N.CANCELADA, 'N') = 'N'
       AND N.IDEMPRESA IN (1) AND  N.PROC = 'S'
      /*FILTROCFOP*/
    UNION ALL  
    SELECT (SELECT ATIVO FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS ATIVO_VENDA,
           (SELECT ATIVO_COMPRA FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS ATIVO_COMPRA,
           'ENTRADA - NF' AS ORIGEM,
           P.CODBARRA AS CODBARRA,
           TRUNC(N.DTCONTABIL) DTVENDA,
           NP.CODPRODUTO,
           P.DESCRICAO, 
           (NP.QUANTIDADE * NP.FATOREMBAL) AS QTDE_ENTRADA,
           (NP.QUANTIDADE * NP.VRCUSTO) AS VALOR_ENTRADA,
           0 AS QTDE_SAIDA,
           0 AS VALOR_SAIDA,
           N.IDEMPRESA, (SELECT  VRCUSTOREP FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS VRCUSTOREP,
		   (SELECT  VRVENDA FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS VRVENDA, P.FATORCX ,
       D.DESCRICAO DEPARTAMENTO,
       G.DESCRICAO GRUPO,
       SG.DESCRICAO SUBGRUPO,
       SE.DESCRICAO SECAO,
       P.CODFOR,
       PAR.RAZAO DESCRICAO_FORN
    FROM NF N 
    LEFT JOIN NF_PROD       NP ON NP.CODNF       = N.CODNF
    LEFT JOIN PRODUTOS       P ON P.IDPRODUTO    = NP.CODPRODUTO
    LEFT JOIN FAMILIAS_PROD  D ON D.CODFAMILIA   = P.CODDPTO
    LEFT JOIN FAMILIAS_PROD  G ON G.CODFAMILIA   = P.CODGRUPO
    LEFT JOIN FAMILIAS_PROD SG ON SG.CODFAMILIA  = P.CODSUBGRUPO
    LEFT JOIN FAMILIAS_PROD SE ON SE.CODFAMILIA  = P.CODSECAO
    LEFT JOIN PARCEIROS     PA ON PA.CODPARCEIRO = N.CODPARCEIRO     
    LEFT JOIN PARCEIROS PAR    ON PAR.CODPARCEIRO = P.CODFOR
    WHERE N.TIPO = 'E' 
    AND TRUNC(N.DTCONTABIL) BETWEEN :D1 AND :D2
    AND COALESCE(N.CANCELADA, 'N') = 'N' AND N.CFOP NOT IN ('2411','2202','2204','1202','1204','1411','2553','1553','1209','1918','2209','2918')
       AND N.IDEMPRESA IN (1) AND  N.PROC = 'S' 
      /*FILTROCFOP*/
    UNION ALL  
    SELECT (SELECT ATIVO FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS ATIVO_VENDA,
           (SELECT ATIVO_COMPRA FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS ATIVO_COMPRA, 
           'VENDAS - PDV' AS ORIGEM, 
           P.CODBARRA,
           TRUNC(N.DTVENDA) DTVENDA,
           N.CODPRODUTO, 
           P.DESCRICAO,
           0 AS QTDE_ENTRADA,
           0 AS VALOR_ENTRADA,       
           N.QTDE AS QTDE_SAIDA,
           CASE 
              WHEN N.IAT = 'A' 
                   THEN CAST((N.QTDE * N.VRVENDA) AS NUMERIC(18,2)) 
                   ELSE (CAST(TRUNC((N.QTDE * N.VRVENDA) * 100) AS NUMERIC(18,2)) / 100)
           END AS VALOR_SAIDA,
           N.IDEMPRESA,  (SELECT  VRCUSTOREP FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS VRCUSTOREP,
		   (SELECT  VRVENDA FROM MULTI_PRECO M WHERE M.IDPRODUTO = P.IDPRODUTO AND M.IDEMPRESA = N.IDEMPRESA) AS VRVENDA, P.FATORCX ,
       D.DESCRICAO DEPARTAMENTO,
       G.DESCRICAO GRUPO,
       SG.DESCRICAO SUBGRUPO,
       SE.DESCRICAO SECAO,
       P.CODFOR,
       PAR.RAZAO DESCRICAO_FORN
    FROM VENDAS N
    LEFT JOIN PRODUTOS       P ON P.IDPRODUTO    = N.CODPRODUTO
    LEFT JOIN FAMILIAS_PROD  D ON D.CODFAMILIA   = P.CODDPTO
    LEFT JOIN FAMILIAS_PROD  G ON G.CODFAMILIA   = P.CODGRUPO
    LEFT JOIN FAMILIAS_PROD SG ON SG.CODFAMILIA  = P.CODSUBGRUPO
    LEFT JOIN FAMILIAS_PROD SE ON SE.CODFAMILIA  = P.CODSECAO
    LEFT JOIN PARCEIROS     PA ON PA.CODPARCEIRO = N.CODPARCEIRO 
    LEFT JOIN PARCEIROS PAR    ON PAR.CODPARCEIRO = P.CODFOR
    WHERE TRUNC(N.DTVENDA) BETWEEN :D1 AND :D2
    AND COALESCE(N.CANCELADO, 'N') = 'N'
     AND N.IDEMPRESA IN (1)
    /*FILTROCFOPVENDA*/
  )
  GROUP BY ATIVO_VENDA,
            ATIVO_COMPRA,
            CODBARRA,
           DTVENDA,
           CODPRODUTO,
           DESCRICAO,
           IDEMPRESA,
           VRCUSTOREP,
           VRVENDA, 
           FATORCX, 
           ORIGEM,
           DEPARTAMENTO,
           GRUPO,
           SUBGRUPO,
           SESSAO,
           CODFOR,
           DESCRICAO_FORN
) CURR
LEFT JOIN EMPRESAS    EM ON EM.CODEMPRESA = CURR.IDEMPRESA
GROUP BY ATIVO_VENDA,
       ATIVO_COMPRA,
       CURR.CODBARRA,
         --CURR.DTVENDA,
         CURR.CODPRODUTO,
         CURR.DESCRICAO,
         CURR.IDEMPRESA,
         EM.FANTASIA,  VRCUSTOREP, VRVENDA, FATORCX,
         DEPARTAMENTO,
         GRUPO,
         SUBGRUPO,
         SESSAO,
         CODFOR,
         DESCRICAO_FORN
ORDER BY IDEMPRESA, DESCRICAO
--REGISTRO 
 --NOVAEXP  AND N.IDEMPRESA IN (1) FIMNOVAEXP-- 
 --ANTIGAEXP /*FILTROVENDAS*/ FIMANTIGAEXP-- 