-- FONTE DA PROCEDURE (ALL_SOURCE da produção, somente leitura), 06/10/2026 — POE_REL_PRECOS_ALTERADOS
-- Chamada pela origem 'Lote de preço detalhado' do FRMRELPRECOSALTERADOS; grava REL_PRECOS_ALTERADOS_01 (ver uRelPrecosAlterados.md).
PROCEDURE POE_REL_PRECOS_ALTERADOS(
   DT_INI VARCHAR2,
   DT_FIM VARCHAR2,
   EMPRESA_1 NUMBER,
   EMPRESA_2 NUMBER,
   EMPRESA_3 NUMBER,
   EMPRESA_4 NUMBER,
   EMPRESA_5 NUMBER,
   EMPRESA_6 NUMBER,
   EMPRESA_7 NUMBER,
   EMPRESA_8 NUMBER,
   EMPRESA_9 NUMBER,
   EMPRESA_10 NUMBER,
   PROMO VARCHAR2,
   EMP VARCHAR2,
   MODELO NUMBER ,
   GRUPOPRECO VARCHAR2
)
IS
BEGIN
   DELETE FROM REL_PRECOS_ALTERADOS_01;
   DELETE FROM AUX_PRECO_ALTERADO;

   INSERT INTO AUX_PRECO_ALTERADO (SELECT TRIM(SUBSTR(OBS,33, 10)), IDPRODUTO, CODLOTEPRECO FROM LOTEPRECO WHERE TRUNC(DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10)) AND OBS LIKE 'REFERENTE A NOTA FISCAL DE NRO%');

   IF(MODELO = 1) THEN
     IF(PROMO = 'S') THEN
       INSERT INTO REL_PRECOS_ALTERADOS_01(CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO)
       SELECT CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO FROM (
        SELECT ROWNUM CODIGO,  E.CODEMPRESA, E.FANTASIA, F.DESCRICAO DPTO,M.IDPRODUTO,  P.DESCRICAO,
        COALESCE(M.VRVENDA, 0) VALORLOTE, COALESCE(I.VRVENDA, 0) VENDAATUAL, COALESCE(I.PROMOCAO, 'N') PROMOCAO ,COALESCE(I.VRPROMO, 0) VRPROMO,
        (SELECT TRUNC(A.DTINICIOPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1  ) DTINI,
        (SELECT TRUNC(A.DTFIMPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1 ) DTFIM,
        MAX(NP.VRVENDASUG) VRVENDASUG,
         COALESCE(I.VRCUSTOREP, COALESCE(I.VRCUSTO, 0)) CUSTOATUAL,
         MAX(NP.ULTCUSTO) ULTCUSTO,
         CASE  SUBSTR(M.OBS,1, 23) WHEN 'REFERENTE A NOTA FISCAL'
         THEN
           MAX(NF.USULTALTERACAO)||'-'||OPE.LOGIN
         ELSE
          TRIM(SUBSTR(M.OBS,68, 40)) END USUARIO
        FROM LOTEPRECO M
        LEFT JOIN PRODUTOS P ON (M.IDPRODUTO = P.IDPRODUTO)
        LEFT JOIN MULTI_PRECO I ON I.IDPRODUTO = M.IDPRODUTO AND I.IDEMPRESA = M.CODEMPRESA
        LEFT JOIN FAMILIAS_PROD F ON (F.CODFAMILIA = P.CODDPTO)
        LEFT JOIN EMPRESAS E ON (M.CODEMPRESA = E.CODEMPRESA)
        LEFT JOIN AUX_PRECO_ALTERADO A ON A.CODLOTEPRECO = M.CODLOTEPRECO
        LEFT JOIN NF ON NF.NRONF = A.NRONF AND ((TRUNC(NF.DTULTIMALTERACAO) = TRUNC(M.DATALOTE)) OR (TRUNC(NF.DTCONTABIL) = TRUNC(M.DATALOTE))) AND ROWNUM = 1
        LEFT JOIN NF_PROD NP ON NP.CODNF = NF.CODNF AND NP.CODPRODUTO = M.IDPRODUTO
        LEFT JOIN OPERADORES OPE ON OPE.CODOPERADOR = NF.USULTALTERACAO

        WHERE TRUNC(M.DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10))
        AND M.CODEMPRESA IN(EMPRESA_1, EMPRESA_2, EMPRESA_3, EMPRESA_4, EMPRESA_5,
                            EMPRESA_6, EMPRESA_7, EMPRESA_8, EMPRESA_9, EMPRESA_10)
        AND COALESCE(I.PROMOCAO,'N') = CAST(PROMO AS VARCHAR2(1)) AND ((COALESCE(NP.CODNF, 0) <> 0) OR (M.OBS LIKE 'REFERENTE AO PEDIDO%') OR (M.OBS LIKE 'REFERENTE AO AJUSTE NO CADASTRO%'))
        GROUP BY ROWNUM, E.CODEMPRESA,  E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO,  P.IDPRODUTO,
        M.IDPRODUTO, M.CODEMPRESA, M.OBS, M.VRVENDA, I.VRVENDA , I.VRCUSTO, I.VRCUSTOREP , I.VRPROMO, I.PROMOCAO, I.IDEMPRESA, OPE.LOGIN
        ORDER BY E.CODEMPRESA,   E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO, M.OBS
      ) GROUP BY CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO;
    ELSE IF(PROMO = 'N') THEN
       INSERT INTO REL_PRECOS_ALTERADOS_01(CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO)
       SELECT CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO FROM (
        SELECT ROWNUM CODIGO,  E.CODEMPRESA, E.FANTASIA, F.DESCRICAO DPTO,M.IDPRODUTO,  P.DESCRICAO,
        COALESCE(M.VRVENDA, 0) VALORLOTE, COALESCE(I.VRVENDA, 0) VENDAATUAL, COALESCE(I.PROMOCAO, 'N') PROMOCAO ,COALESCE(I.VRPROMO, 0) VRPROMO,
        (SELECT TRUNC(A.DTINICIOPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1  ) DTINI,
        (SELECT TRUNC(A.DTFIMPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1 ) DTFIM,
        MAX(NP.VRVENDASUG) VRVENDASUG,
         COALESCE(I.VRCUSTOREP, COALESCE(I.VRCUSTO, 0)) CUSTOATUAL,
         MAX(NP.ULTCUSTO) ULTCUSTO,
         CASE  SUBSTR(M.OBS,1, 23) WHEN 'REFERENTE A NOTA FISCAL'
         THEN
           MAX(NF.USULTALTERACAO)||'-'||OPE.LOGIN
         ELSE
          TRIM(SUBSTR(M.OBS,68, 40)) END USUARIO
        FROM LOTEPRECO M
        LEFT JOIN PRODUTOS P ON (M.IDPRODUTO = P.IDPRODUTO)
        LEFT JOIN MULTI_PRECO I ON I.IDPRODUTO = M.IDPRODUTO AND I.IDEMPRESA = M.CODEMPRESA
        LEFT JOIN FAMILIAS_PROD F ON (F.CODFAMILIA = P.CODDPTO)
        LEFT JOIN EMPRESAS E ON (M.CODEMPRESA = E.CODEMPRESA)
        LEFT JOIN AUX_PRECO_ALTERADO A ON A.CODLOTEPRECO = M.CODLOTEPRECO
        LEFT JOIN NF ON NF.NRONF = A.NRONF AND ((TRUNC(NF.DTULTIMALTERACAO) = TRUNC(M.DATALOTE)) OR (TRUNC(NF.DTCONTABIL) = TRUNC(M.DATALOTE))) AND ROWNUM = 1
        LEFT JOIN NF_PROD NP ON NP.CODNF = NF.CODNF AND NP.CODPRODUTO = M.IDPRODUTO
        LEFT JOIN OPERADORES OPE ON OPE.CODOPERADOR = NF.USULTALTERACAO

        WHERE TRUNC(M.DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10))
        AND M.CODEMPRESA IN(EMPRESA_1, EMPRESA_2, EMPRESA_3, EMPRESA_4, EMPRESA_5,
                            EMPRESA_6, EMPRESA_7, EMPRESA_8, EMPRESA_9, EMPRESA_10)
        AND COALESCE(I.PROMOCAO,'N') = CAST(PROMO AS VARCHAR2(1)) AND ((COALESCE(NP.CODNF, 0) <> 0) OR (M.OBS LIKE 'REFERENTE AO PEDIDO%') OR (M.OBS LIKE 'REFERENTE AO AJUSTE NO CADASTRO%'))
        GROUP BY ROWNUM, E.CODEMPRESA,  E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO,  P.IDPRODUTO,
        M.IDPRODUTO, M.CODEMPRESA, M.OBS, M.VRVENDA, I.VRVENDA , I.VRCUSTO,I.VRCUSTOREP , I.VRPROMO, I.PROMOCAO, I.IDEMPRESA, OPE.LOGIN
        ORDER BY E.CODEMPRESA,   E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO, M.OBS
      ) GROUP BY CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO;
    ELSE
       INSERT INTO REL_PRECOS_ALTERADOS_01(CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO)
       SELECT CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO FROM (
        SELECT ROWNUM CODIGO,  E.CODEMPRESA, E.FANTASIA, F.DESCRICAO DPTO,M.IDPRODUTO,  P.DESCRICAO,
        COALESCE(M.VRVENDA, 0) VALORLOTE, COALESCE(I.VRVENDA, 0) VENDAATUAL, COALESCE(I.PROMOCAO, 'N') PROMOCAO ,COALESCE(I.VRPROMO, 0) VRPROMO,
        (SELECT TRUNC(A.DTINICIOPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1  ) DTINI,
        (SELECT TRUNC(A.DTFIMPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1 ) DTFIM,
         MAX(NP.VRVENDASUG) VRVENDASUG,
         COALESCE(I.VRCUSTOREP, COALESCE(I.VRCUSTO, 0)) CUSTOATUAL,
         MAX(NP.ULTCUSTO) ULTCUSTO,
         CASE  SUBSTR(M.OBS,1, 23) WHEN 'REFERENTE A NOTA FISCAL'
         THEN
           MAX(NF.USULTALTERACAO)||'-'||OPE.LOGIN
         ELSE
          TRIM(SUBSTR(M.OBS,68, 40)) END USUARIO
        FROM LOTEPRECO M
        LEFT JOIN PRODUTOS P ON (M.IDPRODUTO = P.IDPRODUTO)
        LEFT JOIN MULTI_PRECO I ON I.IDPRODUTO = M.IDPRODUTO AND I.IDEMPRESA = M.CODEMPRESA
        LEFT JOIN FAMILIAS_PROD F ON (F.CODFAMILIA = P.CODDPTO)
        LEFT JOIN EMPRESAS E ON (M.CODEMPRESA = E.CODEMPRESA)
        LEFT JOIN AUX_PRECO_ALTERADO A ON A.CODLOTEPRECO = M.CODLOTEPRECO
        LEFT JOIN NF ON NF.NRONF = A.NRONF AND ((TRUNC(NF.DTULTIMALTERACAO) = TRUNC(M.DATALOTE)) OR (TRUNC(NF.DTCONTABIL) = TRUNC(M.DATALOTE))) AND ROWNUM = 1
        LEFT JOIN NF_PROD NP ON NP.CODNF = NF.CODNF AND NP.CODPRODUTO = M.IDPRODUTO
        LEFT JOIN OPERADORES OPE ON OPE.CODOPERADOR = NF.USULTALTERACAO

        WHERE TRUNC(M.DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10))
        AND M.CODEMPRESA IN(EMPRESA_1, EMPRESA_2, EMPRESA_3, EMPRESA_4, EMPRESA_5,
                            EMPRESA_6, EMPRESA_7, EMPRESA_8, EMPRESA_9, EMPRESA_10) AND ((COALESCE(NP.CODNF, 0) <> 0) OR (M.OBS LIKE 'REFERENTE AO PEDIDO%') OR (M.OBS LIKE 'REFERENTE AO AJUSTE NO CADASTRO%'))
      --AND COALESCE(I.PROMOCAO,'N') = CAST(PROMO AS VARCHAR2(1))
        GROUP BY ROWNUM, E.CODEMPRESA,  E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO,  P.IDPRODUTO,
        M.IDPRODUTO, M.CODEMPRESA, M.OBS, M.VRVENDA, I.VRVENDA , I.VRCUSTO,I.VRCUSTOREP , I.VRPROMO, I.PROMOCAO, I.IDEMPRESA, OPE.LOGIN
        ORDER BY E.CODEMPRESA,   E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO, M.OBS
      ) GROUP BY CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO;
    END IF;
    END IF;

    IF (EMP = 'S') THEN
      DELETE FROM REL_PRECOS_ALTERADOS_01 D
      WHERE  ROWID >
           (SELECT MIN(ROWID) FROM REL_PRECOS_ALTERADOS_01 B
           WHERE B.CODEMPRESA = D.CODEMPRESA
           AND B.DPTO = D.DPTO
           AND B.IDPRODUTO = D.IDPRODUTO
           AND B.DESCRICAO = D.DESCRICAO
           AND B.VALORLOTE = D.VALORLOTE
           AND B.VENDAATUAL = D.VENDAATUAL
           AND B.VRVENDASUG = D.VRVENDASUG
           AND B.CUSTOATUAL = D.CUSTOATUAL
           AND B.ULTCUSTO = D.ULTCUSTO
           AND B.VRPROMO = D.VRPROMO
           AND B.PROMOCAO = D.PROMOCAO);
    ELSE
       DELETE FROM REL_PRECOS_ALTERADOS_01 D
       WHERE  ROWID >
           (SELECT MIN(ROWID) FROM REL_PRECOS_ALTERADOS_01 B
           WHERE B.DPTO = D.DPTO
           AND B.IDPRODUTO = D.IDPRODUTO
           AND B.DESCRICAO = D.DESCRICAO
           AND B.VALORLOTE = D.VALORLOTE
           AND B.VENDAATUAL = D.VENDAATUAL
           AND B.VRVENDASUG = D.VRVENDASUG
           AND B.CUSTOATUAL = D.CUSTOATUAL
           AND B.ULTCUSTO = D.ULTCUSTO
           AND B.VRPROMO = D.VRPROMO
           AND B.PROMOCAO = D.PROMOCAO);
    END IF;
   ELSE
     IF(PROMO = 'S') THEN
       INSERT INTO REL_PRECOS_ALTERADOS_01(CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO,
                                         VENDAANT, ESTOQ, ULTDTVENDA)
       SELECT CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE,VENDAATUAL,PROMOCAO,VRPROMO,DTINI,DTFIM,VRVENDASUG,CUSTOATUAL,ULTCUSTO,USUARIO,VENDAANT,ESTOQ,ULTDTVENDA FROM (
        SELECT ROWNUM CODIGO,  E.CODEMPRESA, E.FANTASIA, F.DESCRICAO DPTO,M.IDPRODUTO,  P.DESCRICAO,
        COALESCE(M.VRVENDA, 0) VALORLOTE, COALESCE(I.VRVENDA, 0) VENDAATUAL, COALESCE(I.PROMOCAO, 'N') PROMOCAO ,COALESCE(I.VRPROMO, 0) VRPROMO,
        (SELECT TRUNC(A.DTINICIOPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1  ) DTINI,
        (SELECT TRUNC(A.DTFIMPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1 ) DTFIM,
        MAX(NP.VRVENDASUG) VRVENDASUG,
         COALESCE(I.VRCUSTOREP, COALESCE(I.VRCUSTO, 0)) CUSTOATUAL,
         MAX(NP.ULTCUSTO) ULTCUSTO,
         CASE  SUBSTR(M.OBS,1, 23) WHEN 'REFERENTE A NOTA FISCAL'
         THEN
           MAX(NF.USULTALTERACAO)||'-'||OPE.LOGIN
         ELSE
          TRIM(SUBSTR(M.OBS,68, 40)) END USUARIO,
        MAX(NP.ULTVENDA)  VENDAANT,
        COALESCE(MAX(ES.QTDE),0) ESTOQ,
        MAX(NF.DTCONTABIL) ULTDTVENDA
        FROM LOTEPRECO M
        LEFT JOIN PRODUTOS P ON (M.IDPRODUTO = P.IDPRODUTO)
        LEFT JOIN MULTI_PRECO I ON I.IDPRODUTO = M.IDPRODUTO AND I.IDEMPRESA = M.CODEMPRESA
        LEFT JOIN FAMILIAS_PROD F ON (F.CODFAMILIA = P.CODDPTO)
        LEFT JOIN EMPRESAS E ON (M.CODEMPRESA = E.CODEMPRESA)
        LEFT JOIN ESTOQUE ES ON(P.IDPRODUTO = ES.IDPRODUTO AND M.CODEMPRESA = ES.IDEMPRESA)
        LEFT JOIN AUX_PRECO_ALTERADO A ON A.CODLOTEPRECO = M.CODLOTEPRECO
        LEFT JOIN NF ON NF.NRONF = A.NRONF AND ((TRUNC(NF.DTULTIMALTERACAO) = TRUNC(M.DATALOTE)) OR (TRUNC(NF.DTCONTABIL) = TRUNC(M.DATALOTE))) AND ROWNUM = 1
        LEFT JOIN NF_PROD NP ON NP.CODNF = NF.CODNF AND NP.CODPRODUTO = M.IDPRODUTO
        LEFT JOIN OPERADORES OPE ON OPE.CODOPERADOR = NF.USULTALTERACAO
        WHERE TRUNC(M.DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10))
        AND M.CODEMPRESA IN(EMPRESA_1, EMPRESA_2, EMPRESA_3, EMPRESA_4, EMPRESA_5,
                            EMPRESA_6, EMPRESA_7, EMPRESA_8, EMPRESA_9, EMPRESA_10)
        AND COALESCE(I.PROMOCAO,'N') = CAST(PROMO AS VARCHAR2(1)) AND ((COALESCE(NP.CODNF, 0) <> 0) OR (M.OBS LIKE 'REFERENTE AO PEDIDO%') OR (M.OBS LIKE 'REFERENTE AO AJUSTE NO CADASTRO%'))
        GROUP BY ROWNUM, E.CODEMPRESA,  E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO,  P.IDPRODUTO,
        M.IDPRODUTO, M.CODEMPRESA, M.OBS, M.VRVENDA, I.VRVENDA , I.VRCUSTO,I.VRCUSTOREP , I.VRPROMO, I.PROMOCAO, I.IDEMPRESA, OPE.LOGIN
        ORDER BY E.CODEMPRESA,   E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO, M.OBS
      ) GROUP BY CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE,VENDAATUAL,PROMOCAO,VRPROMO,DTINI,DTFIM,VRVENDASUG,CUSTOATUAL,ULTCUSTO,USUARIO,VENDAANT,ESTOQ,ULTDTVENDA;
    ELSE IF(PROMO = 'N') THEN
       INSERT INTO REL_PRECOS_ALTERADOS_01(CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO,
                                           VENDAANT, ESTOQ, ULTDTVENDA)
       SELECT CODIGO,CODEMPRESA,FANTASIA,DPTO,IDPRODUTO,DESCRICAO,VALORLOTE,VENDAATUAL,PROMOCAO,VRPROMO,DTINI,DTFIM,VRVENDASUG,CUSTOATUAL,ULTCUSTO,USUARIO,VENDAANT,ESTOQ,ULTDTVENDA FROM (
        SELECT ROWNUM CODIGO,  E.CODEMPRESA, E.FANTASIA, F.DESCRICAO DPTO,M.IDPRODUTO,  P.DESCRICAO,
        COALESCE(M.VRVENDA, 0) VALORLOTE, COALESCE(I.VRVENDA, 0) VENDAATUAL, COALESCE(I.PROMOCAO, 'N') PROMOCAO ,COALESCE(I.VRPROMO, 0) VRPROMO,
        (SELECT TRUNC(A.DTINICIOPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1  ) DTINI,
        (SELECT TRUNC(A.DTFIMPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1 ) DTFIM,
        MAX(NP.VRVENDASUG) VRVENDASUG,
         COALESCE(I.VRCUSTOREP, COALESCE(I.VRCUSTO, 0)) CUSTOATUAL,
         MAX(NP.ULTCUSTO) ULTCUSTO,
         CASE  SUBSTR(M.OBS,1, 23) WHEN 'REFERENTE A NOTA FISCAL'
         THEN
           MAX(NF.USULTALTERACAO)||'-'||OPE.LOGIN
         ELSE
          TRIM(SUBSTR(M.OBS,68, 40)) END USUARIO,
        MAX(NP.ULTVENDA)  VENDAANT,
        COALESCE(MAX(ES.QTDE),0) ESTOQ,
        MAX(NF.DTCONTABIL) ULTDTVENDA
        FROM LOTEPRECO M
        LEFT JOIN PRODUTOS P ON (M.IDPRODUTO = P.IDPRODUTO)
        LEFT JOIN MULTI_PRECO I ON I.IDPRODUTO = M.IDPRODUTO AND I.IDEMPRESA = M.CODEMPRESA
        LEFT JOIN FAMILIAS_PROD F ON (F.CODFAMILIA = P.CODDPTO)
        LEFT JOIN EMPRESAS E ON (M.CODEMPRESA = E.CODEMPRESA)
        LEFT JOIN ESTOQUE ES ON(P.IDPRODUTO = ES.IDPRODUTO AND M.CODEMPRESA = ES.IDEMPRESA)
        LEFT JOIN AUX_PRECO_ALTERADO A ON A.CODLOTEPRECO = M.CODLOTEPRECO
        LEFT JOIN NF ON NF.NRONF = A.NRONF AND ((TRUNC(NF.DTULTIMALTERACAO) = TRUNC(M.DATALOTE)) OR (TRUNC(NF.DTCONTABIL) = TRUNC(M.DATALOTE))) AND ROWNUM = 1
        LEFT JOIN NF_PROD NP ON NP.CODNF = NF.CODNF AND NP.CODPRODUTO = M.IDPRODUTO
        LEFT JOIN OPERADORES OPE ON OPE.CODOPERADOR = NF.USULTALTERACAO
        WHERE TRUNC(M.DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10))
        AND M.CODEMPRESA IN(EMPRESA_1, EMPRESA_2, EMPRESA_3, EMPRESA_4, EMPRESA_5,
                            EMPRESA_6, EMPRESA_7, EMPRESA_8, EMPRESA_9, EMPRESA_10)
        AND COALESCE(I.PROMOCAO,'N') = CAST(PROMO AS VARCHAR2(1)) AND ((COALESCE(NP.CODNF, 0) <> 0) OR (M.OBS LIKE 'REFERENTE AO PEDIDO%') OR (M.OBS LIKE 'REFERENTE AO AJUSTE NO CADASTRO%'))
        GROUP BY ROWNUM, E.CODEMPRESA,  E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO,  P.IDPRODUTO,
        M.IDPRODUTO, M.CODEMPRESA, M.OBS, M.VRVENDA, I.VRVENDA , I.VRCUSTO, I.VRCUSTOREP , I.VRPROMO, I.PROMOCAO, I.IDEMPRESA, OPE.LOGIN
        ORDER BY E.CODEMPRESA,   E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO, M.OBS
      ) GROUP BY CODIGO,CODEMPRESA,FANTASIA,DPTO,IDPRODUTO,DESCRICAO,VALORLOTE,VENDAATUAL,PROMOCAO,VRPROMO,DTINI,DTFIM,VRVENDASUG,CUSTOATUAL,ULTCUSTO,USUARIO,VENDAANT,ESTOQ,ULTDTVENDA;
    ELSE
       INSERT INTO REL_PRECOS_ALTERADOS_01(CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL, PROMOCAO, VRPROMO, DTINI, DTFIM, VRVENDASUG, CUSTOATUAL,ULTCUSTO, USUARIO,
                                           VENDAANT, ESTOQ, ULTDTVENDA)
       SELECT CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE, VENDAATUAL,PROMOCAO,VRPROMO,DTINI,DTFIM,VRVENDASUG,CUSTOATUAL,ULTCUSTO,USUARIO,VENDAANT,ESTOQ,ULTDTVENDA FROM (
        SELECT ROWNUM CODIGO,  E.CODEMPRESA, E.FANTASIA, F.DESCRICAO DPTO,M.IDPRODUTO,  P.DESCRICAO,
        COALESCE(M.VRVENDA, 0) VALORLOTE, COALESCE(I.VRVENDA, 0) VENDAATUAL, COALESCE(I.PROMOCAO, 'N') PROMOCAO ,COALESCE(I.VRPROMO, 0) VRPROMO,
        (SELECT TRUNC(A.DTINICIOPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1  ) DTINI,
        (SELECT TRUNC(A.DTFIMPROMOCAO) FROM AGENDA_PROMOCAO_ITENS I
         LEFT JOIN AGENDA_PROMOCAO A ON A.CODAGENDA = I.CODAGENDA
         WHERE I.IDPRODUTO = M.IDPRODUTO AND A.FLAGPROMOCAO = 'E' AND I.IDEMPRESA = M.CODEMPRESA AND ROWNUM = 1 ) DTFIM,
        MAX(NP.VRVENDASUG) VRVENDASUG,
         COALESCE(I.VRCUSTOREP, COALESCE(I.VRCUSTO, 0)) CUSTOATUAL,
         MAX(NP.ULTCUSTO) ULTCUSTO,
         CASE  SUBSTR(M.OBS,1, 23) WHEN 'REFERENTE A NOTA FISCAL'
         THEN
           MAX(NF.USULTALTERACAO)||'-'||OPE.LOGIN
         ELSE
          TRIM(SUBSTR(M.OBS,68, 40)) END USUARIO,
        MAX(NP.ULTVENDA)  VENDAANT,
        COALESCE(MAX(ES.QTDE),0) ESTOQ,
        MAX(NF.DTCONTABIL) ULTDTVENDA
        FROM LOTEPRECO M
        LEFT JOIN PRODUTOS P ON (M.IDPRODUTO = P.IDPRODUTO)
        LEFT JOIN MULTI_PRECO I ON I.IDPRODUTO = M.IDPRODUTO AND I.IDEMPRESA = M.CODEMPRESA
        LEFT JOIN FAMILIAS_PROD F ON (F.CODFAMILIA = P.CODDPTO)
        LEFT JOIN EMPRESAS E ON (M.CODEMPRESA = E.CODEMPRESA)
        LEFT JOIN ESTOQUE ES ON(P.IDPRODUTO = ES.IDPRODUTO AND M.CODEMPRESA = ES.IDEMPRESA)
        LEFT JOIN AUX_PRECO_ALTERADO A ON A.CODLOTEPRECO = M.CODLOTEPRECO
        LEFT JOIN NF ON NF.NRONF = A.NRONF AND ((TRUNC(NF.DTULTIMALTERACAO) = TRUNC(M.DATALOTE)) OR (TRUNC(NF.DTCONTABIL) = TRUNC(M.DATALOTE))) AND ROWNUM = 1
        LEFT JOIN NF_PROD NP ON NP.CODNF = NF.CODNF AND NP.CODPRODUTO = M.IDPRODUTO
        LEFT JOIN OPERADORES OPE ON OPE.CODOPERADOR = NF.USULTALTERACAO
        WHERE TRUNC(M.DATALOTE) BETWEEN CAST(DT_INI AS VARCHAR(10)) AND CAST(DT_FIM AS VARCHAR2(10))
        AND M.CODEMPRESA IN(EMPRESA_1, EMPRESA_2, EMPRESA_3, EMPRESA_4, EMPRESA_5,
                            EMPRESA_6, EMPRESA_7, EMPRESA_8, EMPRESA_9, EMPRESA_10) AND ((COALESCE(NP.CODNF, 0) <> 0) OR (M.OBS LIKE 'REFERENTE AO PEDIDO%') OR (M.OBS LIKE 'REFERENTE AO AJUSTE NO CADASTRO%'))
      --AND COALESCE(I.PROMOCAO,'N') = CAST(PROMO AS VARCHAR2(1))
        GROUP BY ROWNUM, E.CODEMPRESA,  E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO,  P.IDPRODUTO,
        M.IDPRODUTO, M.CODEMPRESA, M.OBS, M.VRVENDA, I.VRVENDA , I.VRCUSTO, I.VRCUSTOREP , I.VRPROMO, I.PROMOCAO, I.IDEMPRESA, OPE.LOGIN
        ORDER BY E.CODEMPRESA,   E.FANTASIA,  P.CODDPTO, F.DESCRICAO, P.DESCRICAO, M.OBS
      ) GROUP BY CODIGO, CODEMPRESA, FANTASIA, DPTO, IDPRODUTO, DESCRICAO, VALORLOTE,VENDAATUAL,PROMOCAO,VRPROMO,DTINI,DTFIM,VRVENDASUG,CUSTOATUAL,ULTCUSTO,USUARIO,VENDAANT,ESTOQ,ULTDTVENDA;
    END IF;
    END IF;

    IF (EMP = 'S') THEN
      DELETE FROM REL_PRECOS_ALTERADOS_01 D
      WHERE  ROWID >
           (SELECT MIN(ROWID) FROM REL_PRECOS_ALTERADOS_01 B
           WHERE B.CODEMPRESA = D.CODEMPRESA
           AND B.DPTO = D.DPTO
           AND B.IDPRODUTO = D.IDPRODUTO
           AND B.DESCRICAO = D.DESCRICAO
           AND B.VALORLOTE = D.VALORLOTE
           AND B.VENDAATUAL = D.VENDAATUAL
           AND B.VRVENDASUG = D.VRVENDASUG
           AND B.CUSTOATUAL = D.CUSTOATUAL
           AND B.ULTCUSTO = D.ULTCUSTO
           AND B.VRPROMO = D.VRPROMO
           AND B.PROMOCAO = D.PROMOCAO
           AND B.VENDAANT = D.VENDAANT
           AND B.ESTOQ = D.ESTOQ
           AND B.ULTDTVENDA = D.ULTDTVENDA);
    ELSE
       DELETE FROM REL_PRECOS_ALTERADOS_01 D
       WHERE  ROWID >
           (SELECT MIN(ROWID) FROM REL_PRECOS_ALTERADOS_01 B
           WHERE B.DPTO = D.DPTO
           AND B.IDPRODUTO = D.IDPRODUTO
           AND B.DESCRICAO = D.DESCRICAO
           AND B.VALORLOTE = D.VALORLOTE
           AND B.VENDAATUAL = D.VENDAATUAL
           AND B.VRVENDASUG = D.VRVENDASUG
           AND B.CUSTOATUAL = D.CUSTOATUAL
           AND B.ULTCUSTO = D.ULTCUSTO
           AND B.VRPROMO = D.VRPROMO
           AND B.PROMOCAO = D.PROMOCAO
           AND B.VENDAANT = D.VENDAANT
           AND B.ESTOQ = D.ESTOQ
           AND B.ULTDTVENDA = D.ULTDTVENDA);
    END IF;
  END IF;
END;

 
 
