-- DEFINIÇÃO DA VIEW (ALL_VIEWS da produção, somente leitura), 06/10/2026 — GET_APAGARBX (lida pelo FRMMOVIMENTACOESDIA)
SELECT DISTINCT TRUNC(A.DTPGTO),
     CAST(('1') AS NUMERIC(13)),
     R.RAZAO,
     P.DUPLICATA,
     TRUNC(P.DTCOMPRA),
     TRUNC(P.DTVENC),
     A.VALORPG,
     CAST(P.VALOR + COALESCE(VENDOR, 0) AS NUMERIC(13,2)) -  COALESCE(DESCONTO, 0) VALOR,
     P.VALOR,
     UPPER(REPLACE(REPLACE(REPLACE(A.OBS,';',' '),CHR(10),' '),CHR(13),' ')),
     UPPER(REPLACE(REPLACE(REPLACE(P.OBS,';',' '),CHR(10),' '),CHR(13),' ')),
     COALESCE(A.ACRE_DESC, 0) -  COALESCE(DESCONTO, 0),
     A.JUROS,
     O.LOGIN,
     A.IDLOTE,
     P.CODPARCEIRO,
     P.IDEMPRESA,
     A.CODAPG,
     A.CODAPGBX,
     A.CODOPBX,
     P.NRPARCELA,
     N.NRONF,
     E.razaosocial,
     COALESCE(P.tipodoc,  '.'),
     PL.CODIREDUZIDO,
     R.codcontabil,
     A.contabilizado,
     (
       SELECT STRING_AGG('Conta: ' | | C.CODCONTA | | ' - ' | | C.TITULAR | | ' ') TITULAR FROM CONTAS_BANCARIAS C
       LEFT JOIN MOV_CONTAS_BANCARIAS M ON M.CODCONTA = C.CODCONTA
       WHERE M.IDLOTE = A.IDLOTE
     ) TITULAR,
         e.fantasia,
     '       'ESPACO,
     (SELECT cnpj_cpf FROM parceiros_end  pt WHERE pt.codparceiro = P.codparceiro AND  COALESCE(ativado, 'S') = 'S' AND ROWNUM = 1 ),
     P.COD_DESCONTO_TITULO,
     P.CODGRUPO_DESCONTO_TITULO,
     A.TX_JUROS,
     	  (SELECT G.DESCRICAO
	   FROM PLC G
		JOIN CX_APAGAR A ON ( A.CODCC = G.CODPLC)
	   WHERE A.CODGRUPO = P.CODGRUPO AND ROWNUM = 1
	  ),
     COALESCE(A.ACRE_DESC, 0) AS ACRESCIMO_DESCONTO, NOME_RETORNO
FROM APAGAR_BX A
LEFT JOIN APAGAR P ON (P.CODAPG = A.CODAPG)
LEFT JOIN NF N ON (N.CODNF = P.IDNF)
LEFT JOIN PARCEIROS R ON (R.CODPARCEIRO = P.CODPARCEIRO)
LEFT JOIN BANCOS B ON (B.CODBCO = P.CODBCO)
LEFT JOIN OPERADORES O ON (O.CODOPERADOR = A.CODOPBX)
LEFT JOIN EMPRESAS E ON (E.codempresa = P.idempresa)
LEFT JOIN PLANO_CONTAS PL ON PL.CODPLANOCONTAS = R.CODCONTABIL_FOR
WHERE P.QUITADA = 'S'
  AND COALESCE(A.INDR, 'I') = 'I'